# Generated by Django 5.1.6 on 2025-03-17 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homestay',
            name='quan_huyen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='homestay.quanhuyen'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homestay',
            name='tinh_tp',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='homestay.tinhtp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homestay',
            name='xa_phuong',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='homestay.xaphuong'),
            preserve_default=False,
        ),
    ]
