# Generated by Django 5.1.6 on 2025-03-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestay', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homestay',
            old_name='address',
            new_name='homestay_address',
        ),
        migrations.RenameField(
            model_name='homestay',
            old_name='name',
            new_name='homestay_name',
        ),
        migrations.AddField(
            model_name='homestay',
            name='decription',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homestay',
            name='owner',
            field=models.ImageField(default=1, upload_to=''),
        ),
    ]
