# Generated by Django 5.1.6 on 2025-03-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestay', '0002_rename_address_homestay_homestay_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homestay',
            name='owner',
            field=models.IntegerField(default=1),
        ),
    ]
