# Generated by Django 5.1.6 on 2025-03-04 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestay', '0003_alter_homestay_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='TinhTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuanHuyen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
                ('tinh_tp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quan_huyen', to='homestay.tinhtp')),
            ],
        ),
        migrations.CreateModel(
            name='XaPhuong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
                ('quan_huyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xa_phuong', to='homestay.quanhuyen')),
            ],
        ),
    ]
