# Generated by Django 5.1.6 on 2025-03-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestay', '0004_tinhtp_quanhuyen_xaphuong'),
    ]

    operations = [
        migrations.AddField(
            model_name='quanhuyen',
            name='loai',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tinhtp',
            name='loai',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xaphuong',
            name='loai',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tinhtp',
            name='ten',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
