# Generated by Django 5.1.6 on 2025-03-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestay', '0005_quanhuyen_loai_tinhtp_loai_xaphuong_loai_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tinhtp',
            name='loai',
        ),
        migrations.AlterField(
            model_name='tinhtp',
            name='ten',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
