# Generated by Django 5.1.6 on 2025-03-04 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homestay', '0006_remove_tinhtp_loai_alter_tinhtp_ten'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quanhuyen',
            name='loai',
        ),
        migrations.RemoveField(
            model_name='xaphuong',
            name='loai',
        ),
    ]
