# Generated by Django 5.1.6 on 2025-03-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestay', '0007_remove_quanhuyen_loai_remove_xaphuong_loai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homestay',
            name='homestay_address',
            field=models.TextField(max_length=500),
        ),
    ]
