# Generated by Django 5.1.6 on 2025-03-05 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestay', '0008_alter_homestay_homestay_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='homestay',
            name='decription',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='homestay',
            name='homestay_address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='homestay',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
